package com.myapp.hibernatejpaCRUDdemo.entity;

import jakarta.persistence.*;

//Define as DataBase Entity
@Entity
//Define as DataBase Table
@Table(name="student")
public class Student {
    //Define columns in this given Database Table
    //define ID as Primary Key to this Table
    //GeneratedValue -> ID Column will be generated by default at the database side.
    //IDENTITY -> Strategy, that will use database identity column for auto iteration.
    //AUTO -> Strategy, that will self pick strategy, depends on given database.
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id")
    private int id;
    @Column(name="first_name")
    private String firstName;

    @Column(name="last_name")
    private String lastName;

    @Column(name="email")
    private String email;

    public Student() {}

    public Student(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return """
                Student[%d]: {%s, %s, %s} 
               """.formatted(id, firstName, lastName, email);
    }
}
